web:
  upload-path: C:/project/blogPicture

spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

# pageHelper
pagehelper:
  helper-dialect: mysql

qq:
  oauth:
    http: http://meiko2021.net.cn/blog/loginByQQ


#mybatis
#mybatis-plus:
#  mapper-locations: classpath:com.personal.blog.mapper*
#  type-aliases-package: com.personal.blog.entity

logging:
  level:
    root: warn
    com.personal.blog: debug
  file:
    name: log/blog.log