
spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mvc:
    static-path-pattern: /**

# pageHelper
pagehelper:
  helper-dialect: mysql

#mybatis
#mybatis-plus:
#  mapper-locations: classpath:com.personal.blog.mapper*
#  type-aliases-package: com.personal.blog.entity

logging:
  level:
    root: warn
    com.personal.blog: debug
  file:
    name: log/blog.log