package com.personal.blog.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * null
 * @author 1056427550
 * @TableName category
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Category implements Serializable {

    @TableId(type = IdType.INPUT)
    private Integer id;

    private String categoryName;

    @TableField(exist = false)
    private List<Blog> blogList = new ArrayList<>();

    public void setBlogList(Blog blog) {
        this.blogList.add(blog);
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category
     *
     * @mbg.generated 2021-01-28 22:02:03
     */
    private static final long serialVersionUID = 1L;
}