package com.personal.blog.entity;

import java.io.Serializable;
import java.util.Date;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * null
 * @author 1056427550
 * @TableName user
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User implements Serializable {

    @TableId(type = IdType.INPUT)
    private Integer id;

    private String username;

    private String password;

    private boolean permission;

    private String avator;

    private Date createDate;

    private Date updateDate;

    private String email;

    private boolean status;

    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated 2021-01-28 22:02:03
     */
    private static final long serialVersionUID = 1L;
}